// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaceDay.API.Data;

#nullable disable

namespace RaceDay.API.Migrations
{
    [DbContext(typeof(RaceDayDbContext))]
    partial class RaceDayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("RaceDay.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DistanceKM")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EntryFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryID");

                    b.HasIndex("EventID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RaceDay.API.Models.Entry", b =>
                {
                    b.Property<int>("EntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntryID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("UserID", "CategoryID")
                        .IsUnique();

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("RaceDay.API.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DistanceKM")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("RegistrationDeadline")
                        .HasColumnType("TEXT");

                    b.HasKey("EventID");

                    b.HasIndex("OrganizerID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RaceDay.API.Models.Result", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryID")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("FinishTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("OverallPosition")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ResultID");

                    b.HasIndex("EntryID")
                        .IsUnique();

                    b.ToTable("Results");
                });

            modelBuilder.Entity("RaceDay.API.Models.Route", b =>
                {
                    b.Property<int>("RouteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DistanceKM")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ElevationGainM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapURL")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("RouteID");

                    b.HasIndex("EventID")
                        .IsUnique();

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("RaceDay.API.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RaceDay.API.Models.Category", b =>
                {
                    b.HasOne("RaceDay.API.Models.Event", "Event")
                        .WithMany("Categories")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RaceDay.API.Models.Entry", b =>
                {
                    b.HasOne("RaceDay.API.Models.Category", "Category")
                        .WithMany("Entries")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaceDay.API.Models.User", "User")
                        .WithMany("Entries")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RaceDay.API.Models.Event", b =>
                {
                    b.HasOne("RaceDay.API.Models.User", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("RaceDay.API.Models.Result", b =>
                {
                    b.HasOne("RaceDay.API.Models.Entry", "Entry")
                        .WithOne("Result")
                        .HasForeignKey("RaceDay.API.Models.Result", "EntryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("RaceDay.API.Models.Route", b =>
                {
                    b.HasOne("RaceDay.API.Models.Event", "Event")
                        .WithOne("Route")
                        .HasForeignKey("RaceDay.API.Models.Route", "EventID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RaceDay.API.Models.Category", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("RaceDay.API.Models.Entry", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("RaceDay.API.Models.Event", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("RaceDay.API.Models.User", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
